language: python

python:
  - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls

script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - coverage run --source='.' ./manage.py test 
  - coverage report

after_script:
  - coveralls