language: python

python:
  - "3.6"

#service:
  #- postgresql

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls

#before_script:
 #- python manage.py makemigrations
  #- python manage.py migrate

script:
  - coverage run --source='.' ./manage.py test 
  - coverage report

after_script:
  - coveralls
  